//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumersInfo
    {
        public System.Guid id_consumersinfo { get; set; }
        public int ID_DB { get; set; }
        public string codeIESBK { get; set; }
        public string codeOKE { get; set; }
        public string addressInfo { get; set; }
        public string phoneInfo { get; set; }
        public string emailInfo { get; set; }
        public Nullable<int> GUIDRTP3 { get; set; }
        public string ContractRTP3 { get; set; }
        public Nullable<int> CenterGUID { get; set; }
        public Nullable<int> SectionGUID { get; set; }
        public Nullable<int> FiderGUID { get; set; }
        public Nullable<int> NodeGUID { get; set; }
        public Nullable<int> LVFiderGUID { get; set; }
        public Nullable<int> Transforms2_Ident { get; set; }
        public Nullable<System.Guid> houseFIASid { get; set; }
    
        public virtual RTP3_DB RTP3_DB { get; set; }
    }
}
