//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_LVConsumers
    {
        public int GUID { get; set; }
        public int ID_DB { get; set; }
        public Nullable<short> onBalance { get; set; }
        public Nullable<short> Phase { get; set; }
        public Nullable<int> TypeLoad { get; set; }
        public Nullable<decimal> Pust { get; set; }
        public Nullable<decimal> CosFi { get; set; }
        public Nullable<int> TypicalLoadCurve { get; set; }
    
        public virtual RTP3_GUID RTP3_GUID { get; set; }
        public virtual RTP3_Owners RTP3_Owners { get; set; }
        public virtual RTP3_TypeLoads RTP3_TypeLoads { get; set; }
        public virtual RTP3_TypicalLoadCurves RTP3_TypicalLoadCurves { get; set; }
        public virtual RTP3_LVConsumersInfo RTP3_LVConsumersInfo { get; set; }
    }
}
