//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_DB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RTP3_DB()
        {
            this.RTP3_GUID = new HashSet<RTP3_GUID>();
            this.RTP3_Structures = new HashSet<RTP3_Structures>();
            this.RTP3_Owners = new HashSet<RTP3_Owners>();
            this.RTP3_References = new HashSet<RTP3_References>();
            this.RTP3_ReferencesTypes = new HashSet<RTP3_ReferencesTypes>();
            this.RTP3_Regions = new HashSet<RTP3_Regions>();
            this.RTP3_TypeLoads = new HashSet<RTP3_TypeLoads>();
            this.RTP3_Manufacturers = new HashSet<RTP3_Manufacturers>();
            this.RTP3_ProvodTypes = new HashSet<RTP3_ProvodTypes>();
            this.RTP3_SwitchGN = new HashSet<RTP3_SwitchGN>();
            this.ConsumersInfo = new HashSet<ConsumersInfo>();
        }
    
        public int ID_DB { get; set; }
        public string caption_bd { get; set; }
        public int id_filial { get; set; }
    
        public virtual Filial Filial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_GUID> RTP3_GUID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_Structures> RTP3_Structures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_Owners> RTP3_Owners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_References> RTP3_References { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_ReferencesTypes> RTP3_ReferencesTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_Regions> RTP3_Regions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_TypeLoads> RTP3_TypeLoads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_Manufacturers> RTP3_Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_ProvodTypes> RTP3_ProvodTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_SwitchGN> RTP3_SwitchGN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumersInfo> ConsumersInfo { get; set; }
    }
}
