//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_Nodes3
    {
        public int GUID_HH { get; set; }
        public int GUID_CH { get; set; }
        public int ID_DB { get; set; }
        public Nullable<int> TypicalLoadCurveCH { get; set; }
    
        public virtual RTP3_GUID RTP3_GUID { get; set; }
        public virtual RTP3_GUID RTP3_GUID1 { get; set; }
        public virtual RTP3_TypicalLoadCurves RTP3_TypicalLoadCurves { get; set; }
    }
}
