//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_TypicalLoadCurves
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RTP3_TypicalLoadCurves()
        {
            this.RTP3_Nodes = new HashSet<RTP3_Nodes>();
            this.RTP3_Nodes3 = new HashSet<RTP3_Nodes3>();
            this.RTP3_LVConsumers = new HashSet<RTP3_LVConsumers>();
        }
    
        public int ID_DB { get; set; }
        public int Ident { get; set; }
        public string Name { get; set; }
        public decimal Unom { get; set; }
        public int LoadType { get; set; }
        public double kzap1 { get; set; }
        public double sqrKfg1 { get; set; }
        public double kzap2 { get; set; }
        public double sqrKfg2 { get; set; }
        public string Comment { get; set; }
    
        public virtual RTP3_Unom RTP3_Unom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_Nodes> RTP3_Nodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_Nodes3> RTP3_Nodes3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_LVConsumers> RTP3_LVConsumers { get; set; }
    }
}
