//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RTP3ESHEntities : DbContext
    {
        public RTP3ESHEntities()
            : base("name=RTP3ESHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Filial> Filial { get; set; }
        public virtual DbSet<RTP3_AOEnergo> RTP3_AOEnergo { get; set; }
        public virtual DbSet<RTP3_Centers> RTP3_Centers { get; set; }
        public virtual DbSet<RTP3_Coors> RTP3_Coors { get; set; }
        public virtual DbSet<RTP3_DB> RTP3_DB { get; set; }
        public virtual DbSet<RTP3_Fiders> RTP3_Fiders { get; set; }
        public virtual DbSet<RTP3_GUID> RTP3_GUID { get; set; }
        public virtual DbSet<RTP3_Owners> RTP3_Owners { get; set; }
        public virtual DbSet<RTP3_PES> RTP3_PES { get; set; }
        public virtual DbSet<RTP3_References> RTP3_References { get; set; }
        public virtual DbSet<RTP3_ReferencesTypes> RTP3_ReferencesTypes { get; set; }
        public virtual DbSet<RTP3_Regions> RTP3_Regions { get; set; }
        public virtual DbSet<RTP3_RES> RTP3_RES { get; set; }
        public virtual DbSet<RTP3_Sections> RTP3_Sections { get; set; }
        public virtual DbSet<RTP3_Structures> RTP3_Structures { get; set; }
        public virtual DbSet<RTP3_Unom> RTP3_Unom { get; set; }
        public virtual DbSet<RTP3_Lines> RTP3_Lines { get; set; }
        public virtual DbSet<RTP3_TPType> RTP3_TPType { get; set; }
        public virtual DbSet<RTP3_TypicalLoadCurves> RTP3_TypicalLoadCurves { get; set; }
        public virtual DbSet<RTP3_ExLines> RTP3_ExLines { get; set; }
        public virtual DbSet<RTP3_LVFiders> RTP3_LVFiders { get; set; }
        public virtual DbSet<RTP3_LVLines> RTP3_LVLines { get; set; }
        public virtual DbSet<RTP3_LVNodes> RTP3_LVNodes { get; set; }
        public virtual DbSet<RTP3_Manufacturers> RTP3_Manufacturers { get; set; }
        public virtual DbSet<RTP3_Nodes> RTP3_Nodes { get; set; }
        public virtual DbSet<RTP3_Nodes3> RTP3_Nodes3 { get; set; }
        public virtual DbSet<RTP3_Provods> RTP3_Provods { get; set; }
        public virtual DbSet<RTP3_ProvodTypes> RTP3_ProvodTypes { get; set; }
        public virtual DbSet<RTP3_TypeLoads> RTP3_TypeLoads { get; set; }
        public virtual DbSet<RTP3_DoubleLines> RTP3_DoubleLines { get; set; }
        public virtual DbSet<RTP3_Transforms3> RTP3_Transforms3 { get; set; }
        public virtual DbSet<RTP3_LVConsumers> RTP3_LVConsumers { get; set; }
        public virtual DbSet<RTP3_LVConsumersA> RTP3_LVConsumersA { get; set; }
        public virtual DbSet<RTP3_SwitchGN> RTP3_SwitchGN { get; set; }
        public virtual DbSet<RTP3_SwitchGR> RTP3_SwitchGR { get; set; }
        public virtual DbSet<RTP3_LVConsumersInfo> RTP3_LVConsumersInfo { get; set; }
        public virtual DbSet<RTP3_Transforms2> RTP3_Transforms2 { get; set; }
        public virtual DbSet<ProgramOptions> ProgramOptions { get; set; }
        public virtual DbSet<ConsumersInfo> ConsumersInfo { get; set; }
    }
}
