//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_LVFiders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RTP3_LVFiders()
        {
            this.RTP3_LVNodes = new HashSet<RTP3_LVNodes>();
            this.RTP3_LVLines = new HashSet<RTP3_LVLines>();
        }
    
        public int GUID { get; set; }
        public int OwnerGUID { get; set; }
        public int ID_DB { get; set; }
        public string Name { get; set; }
        public decimal Unom { get; set; }
        public Nullable<int> TypeLoad { get; set; }
        public Nullable<System.DateTime> DBB { get; set; }
        public Nullable<System.DateTime> Dkor { get; set; }
    
        public virtual RTP3_GUID RTP3_GUID { get; set; }
        public virtual RTP3_Unom RTP3_Unom { get; set; }
        public virtual RTP3_Nodes RTP3_Nodes { get; set; }
        public virtual RTP3_TypeLoads RTP3_TypeLoads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_LVNodes> RTP3_LVNodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_LVLines> RTP3_LVLines { get; set; }
    }
}
