//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_SwitchGR
    {
        public int Ident { get; set; }
        public Nullable<int> Manufacturer { get; set; }
        public int SwitchGType { get; set; }
        public int ID_DB { get; set; }
        public decimal Unom { get; set; }
        public string Marka { get; set; }
        public string AddStr { get; set; }
        public Nullable<decimal> Inom { get; set; }
        public Nullable<decimal> Ioff { get; set; }
        public Nullable<decimal> Id { get; set; }
        public Nullable<decimal> It { get; set; }
        public Nullable<decimal> Toff { get; set; }
        public Nullable<decimal> Ton { get; set; }
        public Nullable<short> Hide { get; set; }
    
        public virtual RTP3_Manufacturers RTP3_Manufacturers { get; set; }
        public virtual RTP3_SwitchGN RTP3_SwitchGN { get; set; }
        public virtual RTP3_Unom RTP3_Unom { get; set; }
    }
}
