//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_Nodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RTP3_Nodes()
        {
            this.RTP3_ExLines = new HashSet<RTP3_ExLines>();
            this.RTP3_ExLines1 = new HashSet<RTP3_ExLines>();
            this.RTP3_LVFiders = new HashSet<RTP3_LVFiders>();
        }
    
        public int GUID { get; set; }
        public int OwnerGUID { get; set; }
        public int ID_DB { get; set; }
        public string Info { get; set; }
        public int Transf { get; set; }
        public Nullable<int> PositionOtp { get; set; }
        public Nullable<int> TPType { get; set; }
        public Nullable<short> onBalance { get; set; }
        public Nullable<System.DateTime> DBB { get; set; }
        public Nullable<short> TabOrder { get; set; }
        public Nullable<int> TypicalLoadCurve { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_ExLines> RTP3_ExLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_ExLines> RTP3_ExLines1 { get; set; }
        public virtual RTP3_Fiders RTP3_Fiders { get; set; }
        public virtual RTP3_GUID RTP3_GUID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_LVFiders> RTP3_LVFiders { get; set; }
        public virtual RTP3_References RTP3_References { get; set; }
        public virtual RTP3_TPType RTP3_TPType { get; set; }
        public virtual RTP3_Owners RTP3_Owners { get; set; }
        public virtual RTP3_TypicalLoadCurves RTP3_TypicalLoadCurves { get; set; }
    }
}
