//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_GUID
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RTP3_GUID()
        {
            this.RTP3_Nodes31 = new HashSet<RTP3_Nodes3>();
            this.RTP3_LVConsumersA1 = new HashSet<RTP3_LVConsumersA>();
        }
    
        public int GUID { get; set; }
        public Nullable<int> RELATION_ID { get; set; }
        public int ID_DB { get; set; }
    
        public virtual RTP3_AOEnergo RTP3_AOEnergo { get; set; }
        public virtual RTP3_Centers RTP3_Centers { get; set; }
        public virtual RTP3_Coors RTP3_Coors { get; set; }
        public virtual RTP3_DB RTP3_DB { get; set; }
        public virtual RTP3_Fiders RTP3_Fiders { get; set; }
        public virtual RTP3_PES RTP3_PES { get; set; }
        public virtual RTP3_RES RTP3_RES { get; set; }
        public virtual RTP3_Sections RTP3_Sections { get; set; }
        public virtual RTP3_Lines RTP3_Lines { get; set; }
        public virtual RTP3_Nodes RTP3_Nodes { get; set; }
        public virtual RTP3_LVFiders RTP3_LVFiders { get; set; }
        public virtual RTP3_LVNodes RTP3_LVNodes { get; set; }
        public virtual RTP3_LVLines RTP3_LVLines { get; set; }
        public virtual RTP3_Nodes3 RTP3_Nodes3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_Nodes3> RTP3_Nodes31 { get; set; }
        public virtual RTP3_LVConsumers RTP3_LVConsumers { get; set; }
        public virtual RTP3_LVConsumersA RTP3_LVConsumersA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_LVConsumersA> RTP3_LVConsumersA1 { get; set; }
    }
}
