//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_LVNodes
    {
        public int GUID { get; set; }
        public int OwnerGUID { get; set; }
        public int ID_DB { get; set; }
        public string Info { get; set; }
        public Nullable<short> TabOrder { get; set; }
        public string Name { get; set; }
    
        public virtual RTP3_GUID RTP3_GUID { get; set; }
        public virtual RTP3_LVFiders RTP3_LVFiders { get; set; }
    }
}
