//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_Transforms3
    {
        public string TypeTR { get; set; }
        public decimal Snom { get; set; }
        public string AddStr { get; set; }
        public decimal Pxx { get; set; }
        public decimal PkzBC { get; set; }
        public decimal Ixx { get; set; }
        public decimal UnomB { get; set; }
        public decimal UnomH { get; set; }
        public Nullable<int> NumberOtpB { get; set; }
        public Nullable<decimal> DeltaUotpB { get; set; }
        public Nullable<short> Hide { get; set; }
        public int ID_DB { get; set; }
        public int Ident { get; set; }
        public Nullable<int> Manufacturer { get; set; }
        public decimal Unom { get; set; }
        public decimal UnomC { get; set; }
        public decimal PkzBH { get; set; }
        public decimal PkzCH { get; set; }
        public decimal UkBC { get; set; }
        public decimal UkBH { get; set; }
        public decimal UkCH { get; set; }
        public Nullable<decimal> SobmB { get; set; }
        public Nullable<decimal> SobmC { get; set; }
        public Nullable<decimal> SobmH { get; set; }
        public Nullable<int> NumberOtpC { get; set; }
        public Nullable<decimal> DeltaUotpC { get; set; }
    
        public virtual RTP3_Manufacturers RTP3_Manufacturers { get; set; }
        public virtual RTP3_Unom RTP3_Unom { get; set; }
    }
}
