//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_Unom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RTP3_Unom()
        {
            this.RTP3_Sections = new HashSet<RTP3_Sections>();
            this.RTP3_TypicalLoadCurves = new HashSet<RTP3_TypicalLoadCurves>();
            this.RTP3_LVFiders = new HashSet<RTP3_LVFiders>();
            this.RTP3_ProvodTypes = new HashSet<RTP3_ProvodTypes>();
            this.RTP3_Transforms3 = new HashSet<RTP3_Transforms3>();
            this.RTP3_SwitchGR = new HashSet<RTP3_SwitchGR>();
            this.RTP3_Transforms2 = new HashSet<RTP3_Transforms2>();
        }
    
        public decimal Unom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_Sections> RTP3_Sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_TypicalLoadCurves> RTP3_TypicalLoadCurves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_LVFiders> RTP3_LVFiders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_ProvodTypes> RTP3_ProvodTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_Transforms3> RTP3_Transforms3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_SwitchGR> RTP3_SwitchGR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_Transforms2> RTP3_Transforms2 { get; set; }
    }
}
