//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_Sections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RTP3_Sections()
        {
            this.RTP3_Fiders = new HashSet<RTP3_Fiders>();
        }
    
        public string Name { get; set; }
        public int GUID { get; set; }
        public int OwnerGUID { get; set; }
        public decimal Unom { get; set; }
        public Nullable<decimal> Rc { get; set; }
        public Nullable<decimal> Xc { get; set; }
        public int ID_DB { get; set; }
    
        public virtual RTP3_Centers RTP3_Centers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_Fiders> RTP3_Fiders { get; set; }
        public virtual RTP3_GUID RTP3_GUID { get; set; }
        public virtual RTP3_Unom RTP3_Unom { get; set; }
    }
}
