//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_Transforms2
    {
        public int Ident { get; set; }
        public Nullable<int> Manufacturer { get; set; }
        public int ID_DB { get; set; }
        public decimal Unom { get; set; }
        public string TypeTR { get; set; }
        public decimal Snom { get; set; }
        public string AddStr { get; set; }
        public decimal Uk { get; set; }
        public decimal Pxx { get; set; }
        public decimal Pkz { get; set; }
        public decimal Ixx { get; set; }
        public decimal UnomB { get; set; }
        public decimal UnomH { get; set; }
        public Nullable<int> NumberOtp { get; set; }
        public Nullable<decimal> DeltaUotp { get; set; }
        public Nullable<short> Hide { get; set; }
    
        public virtual RTP3_Manufacturers RTP3_Manufacturers { get; set; }
        public virtual RTP3_Unom RTP3_Unom { get; set; }
    }
}
