//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_Provods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RTP3_Provods()
        {
            this.RTP3_DoubleLines = new HashSet<RTP3_DoubleLines>();
        }
    
        public int Ident { get; set; }
        public Nullable<int> Manufacturer { get; set; }
        public int ProvodType { get; set; }
        public int ID_DB { get; set; }
        public string Marka { get; set; }
        public decimal F { get; set; }
        public string AddStr { get; set; }
        public decimal R0 { get; set; }
        public decimal X0 { get; set; }
        public Nullable<decimal> B0 { get; set; }
        public int Idop { get; set; }
        public Nullable<decimal> G0 { get; set; }
        public Nullable<decimal> TgDelta { get; set; }
        public Nullable<short> Hide { get; set; }
    
        public virtual RTP3_Manufacturers RTP3_Manufacturers { get; set; }
        public virtual RTP3_ProvodTypes RTP3_ProvodTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTP3_DoubleLines> RTP3_DoubleLines { get; set; }
    }
}
