//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_LVConsumersInfo
    {
        public int GUID { get; set; }
        public int ID_DB { get; set; }
        public string PointName { get; set; }
        public string Contract { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string INN { get; set; }
        public string Power { get; set; }
        public Nullable<decimal> Kmeter { get; set; }
        public Nullable<decimal> MeterValue { get; set; }
    
        public virtual RTP3_LVConsumers RTP3_LVConsumers { get; set; }
    }
}
