//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_DoubleLines
    {
        public int GUID { get; set; }
        public int ID_DB { get; set; }
        public int Provod { get; set; }
        public decimal LineLength { get; set; }
        public System.Guid GUID_PK { get; set; }
    
        public virtual RTP3_Lines RTP3_Lines { get; set; }
        public virtual RTP3_Provods RTP3_Provods { get; set; }
    }
}
