//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtp3esh_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_ExLines
    {
        public int GUID1 { get; set; }
        public int GUID2 { get; set; }
        public int ID_DB { get; set; }
        public int State_ { get; set; }
    
        public virtual RTP3_Nodes RTP3_Nodes { get; set; }
        public virtual RTP3_Nodes RTP3_Nodes1 { get; set; }
    }
}
